[package]
name = "d7"
version = "0.1.0"
authors = ["Piotr Kochmanski <piotr.kochmanski@allegro.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"